### ISSUE TITLE
Add "sync" functionality

### ISSUE THREAD

**Issue by kougar** [cnrancher/hangar#11]
执行save操作的时候经常会有失败的，重新下载还需要清空cache目录，并生成另外一个压缩包，用起来体验不好。
希望增加个sync功能，把失败的组件增量补充到上次的cache目录里。后面的打包和压缩命令也可以单独提供。

还可以考虑提供增量压缩包的能力，比如之前给客户提供了2.7.1的压缩包，下个版本2.7.2发布之后只需要增量同步到cache目录，并把增量部分单独压缩后提供给客户。

**Comment by Jason-ZW** [comment]
对于第二点需求增量压缩: RPM的镜像依赖主要来源是KDM和Charts，每个版本的矩阵会有所不同，功能上支持增量会给项目维护带来很重的负担，而且当矩阵版本更新较大时，这个功能显得也有些鸡肋，因此第二点需求研发团队评估后不做支持。

**Comment by STARRY-S** [comment]
Sync subcommand added in commit: https://github.com/cnrancher/hangar/commit/455e9e11cc490eedc013e9a65b917723064b8b9b

**Comment by STARRY-S** [comment]
Available to test in `v1.5.0-rc3`.

**Comment by rootwuj** [comment]
版本：v1.5.0-rc11

验证通过，测试结果参考：[测试用例-镜像推送工具-sync、compress、decompress子命令](https://mysuse.sharepoint.com/:x:/s/QAEngineer/ETtHFyNInqJGlb_oqWOnsdkBhpwZiO3rykknmrR01XlO5Q?e=opc53P)
