### ISSUE TITLE
"load" does not support directory

### ISSUE THREAD

**Issue by kougar** [cnrancher/hangar#12]
load的参数里是这么说的：
  -s string
        saved file to load (tar tarball or a directory)

假如用目录加载出错如下：
❯ ./hangar load -s ./rancher_images_v2.7.1-ent -d harbor.local
13:56:24 [INFO] Found skopeo: skopeo version 0.1.41
13:56:24 [INFO] Decompressing ./rancher_images_v2.7.1-ent...
13:56:24 [INFO] Read "./rancher_images_v2.7.1-ent"
13:56:24 [FATA] Decompress: gzip.NewReader: Read: read ./rancher_images_v2.7.1-ent: is a directory

**Comment by STARRY-S** [comment]
```
-compress=dir
```
