### ISSUE TITLE
cmd: optimize `cmd` related packages

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#13]
Codes in the [cmd](https://github.com/cnrancher/hangar/tree/main/cmd) folder need optimize by replacing the `flag` package with the [cobra](https://github.com/spf13/cobra) package.

----

在旧版本中，Hangar 使用 `flag` 包处理用户输入的命令行参数。
在代码编写方面，不同的子命令之间存在一些可复用的代码，旧版本中命令行参数处理的这部分逻辑有待优化；
在用户使用方面，旧版本的 Help 提示信息不够完善；

因此决定更新 [cmd](https://github.com/cnrancher/hangar/tree/main/cmd) 目录下处理命令行参数相关的代码，改用 [cobra](https://github.com/spf13/cobra) 处理用户输入的命令行参数，并提供更详细的 Help 信息。

----

将 `flag` 更换为 `cobra` 不影响 Hangar 的每个子命令的名称以及所需输入的参数名称。

需要注意的是 `flag` 在处理用户输入的命令行参数时，允许以下几种格式：
```
-f
-flag
--flag   // double dashes are also permitted
-flag=x
-flag x  // non-boolean flags only
```

而更改为 `cobra` 后，按照 POSIX 标准，用户输入的命令行参数格式应类似于：
```
-f
--flag
--flag x
--flag=x
```

**Comment by STARRY-S** [comment]
The `cmd` folder was refactored with `cobra` in commit: https://github.com/cnrancher/hangar/commit/88684290dab0a42b180b0f88856ea189357c0678

**Comment by rootwuj** [comment]
version：v1.5.0-rc5

The command args have been changed to cobra.
