### ISSUE TITLE
Remove unused `stdin` mode for mirror/save command

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#14]
The `stdin` mode was initially used for debugging purposes, but was not useful for users.

This feature will remove in the next release. 

-----

在起初开发 Hangar 时，Mirror 和 Save 命令除了可以从文件中读取镜像列表，为了便于调试，在不指定镜像列表文件时，还支持手动输入镜像列表，因此功能并不实用，将在 1.5 中移除。

**Comment by STARRY-S** [comment]
`stdin` mode was removed in commit: https://github.com/cnrancher/hangar/commit/88684290dab0a42b180b0f88856ea189357c0678

**Comment by STARRY-S** [comment]
Available to test in `v1.5.0-rc3`.

**Comment by rootwuj** [comment]
version：v1.5.0-rc5

使用mirror或save命令，不设置 -f 参数指定镜像列表文件，命令无法执行成功。

```
# ./hangar mirror -d private.registry.io
07:07:13 [INFO] skopeo version 1.9.3
Error: image list file name not specified

# ./hangar save -d saved-images.tar.gz
07:10:03 [INFO] skopeo version 1.9.3
Error: image list file name not specified

```
