### ISSUE TITLE
Consider to remove `helm` & `rancher/rke` dependency to reduce binary size

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#16]
After adding `helm.sh/helm/v3` and `rancher/rke` dependencies to the `generate-list` command, the compiled binary file size increased from 6 MB to around 40 MB.

----

`generate-list` 命令所使用的依赖使得编译后的二进制文件体积增加许多，在考虑不影响功能的情况下，移除相应的依赖，适当减小编译后文件的体积。

**Comment by STARRY-S** [comment]
`helm` & `rancher/rke` dependencies were removed in commit: https://github.com/cnrancher/hangar/commit/86686780d63e69013038ee46693514dd3d1edd9c

**Comment by STARRY-S** [comment]
Available to test in `v1.5.0-rc3`.

**Comment by rootwuj** [comment]
Pass Verified in `v1.5.0-rc5`, the `generate-list` command works fine.

**Comment by STARRY-S** [comment]
由于移除 `helm` 和 `rancher/rke` 依赖后，加载 Chart Index 和 KDM Data 的数据结构需要在代码中单独维护，增加了一定量的开发维护成本难度，这种维护方式并不十分推荐，且编译后的二进制文件体积在 50M 左右，是可以接受的体积大小。
因此最终决定在 `v1.5.0-rc7` 版本中恢复使用 `helm` 和 `rancher/rke` 依赖。

> 已使用 Validation Test 测试过 RC7 版本的全部功能。
