### ISSUE TITLE
[1.4.3][feature] Add OCI format container image support 

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#17]
Need to support OCI format container image (media type: `application/vnd.oci.image.manifest.v1+json`)

And the logic of mirror/load and validation functions needs to be updated.

**Comment by rootwuj** [comment]
**Version:** 
- v1.4.3-rc1


**OCI format container image:**

- quay.io/skopeo/stable:v1.10.0
- cnrancher/global-monitoring-ui:0.1.2
- cnrancher/webhook-receiver:v0.2.7-ent


**Verification passed. The test results are as follows:**

Test Case | Test Result
--|--
Mirror OCI format image | Pass
Save OIC format image | Pass
