### ISSUE TITLE
[1.5][generate-list] Replace `rancher/webhook` to `cnrancher/webhook` when generating 2.7.x-ent images

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#20]
Related issue:  https://github.com/cnrancher/pandaria/pull/2885

在生成 2.7.2-ent 及后续版本的镜像列表时，将 `rancher/webhook` 镜像替换为 GC 使用的 `cnrancher/webhook`。

**Comment by STARRY-S** [comment]
对应 commit：https://github.com/cnrancher/hangar/commit/587818ba7ae12474ccbfb1892b79041bd8ffc4c5
可在下一个 RC 版本中进行测试。

**Comment by rootwuj** [comment]
版本：v1.5.0-rc5

验证通过。使用工具生成 v2.7.2-ent 的镜像列表时，会替换webhook镜像为cnrancher/webhook

v2.7.2-ent logs：
```
06:33:31 [INFO] Replaced "rancher/rancher-webhook:v0.3.3" to "cnrancher/rancher-webhook:v0.3.3"
```
