### ISSUE TITLE
支持 HTTP & Skip TLS Verify 功能

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#21]
1. 目前 Hangar 不支持 HTTP Harbor Registry，仅支持 HTTPS Harbor Registry，需要添加 HTTP 类型的 Registry 支持。
2. 除此之外，在使用自签名 Harbor 时，目前文档中配置 Harbor 使用自签名的步骤比较繁琐，且要求证书中包括 IP SANs 内容，此部分可以优化，添加 skip tls verify 跳过签名证书校验。

**Comment by STARRY-S** [comment]
相关 Issue：https://github.com/cnrancher/hangar/issues/22

计划移除掉 Hangar 的 `docker` 和 `docker-buildx` 第三方依赖，以实现 skip-tls-verify 和 HTTP Private Registry 支持，之后在容器内只需要执行 `skopeo login`，不需要 `docker login`。

**Comment by wangzheivan** [comment]
目前客户发现，在主机上安装shopeo之后，使用skopeo login 也是登录不了的

**Comment by STARRY-S** [comment]
功能开发完毕并完成自测 & Validation Test，使用文档已更新：https://github.com/cnrancher/hangar/blob/v1.6.0-rc3/docs/zh_CN/README.md

后续版本在向 HTTP 或使用自签名的 Registry 仓库 Mirror / Save / Load 镜像时，可通过添加 `--tls-verify=false` 参数跳过 TLS 验证。

可在 `v1.6.0-rc3` 及后续 RC 版本中测试。
CC @rootwuj

**Comment by rootwuj** [comment]
## 版本：
- hangar: v1.6.0-rc5
- harbor: v2.8.1
- skopeo: 1.9.3、1.12.0

## 测试场景：

Harbor地址 | 二进制文件运行 | 容器镜像运行
-- | -- | --
http带端口 | 1. Mirror镜像成功 </br> 2.   Save、Load镜像成功 | 1. Mirror镜像成功 </br> 2.   Save、Load镜像成功
http不带端口 | 1. Mirror镜像成功 </br> 2.   Save、Load镜像成功 | 1. Mirror镜像成功 </br> 2.   Save、Load镜像成功
https自签名证书 | 1. Mirror镜像成功 </br> 2.   Save、Load镜像成功 | 1. Mirror镜像成功 </br> 2.   Save、Load镜像成功



## 执行的命令：

### harbor http

Mirror
```
hangar convert-list -i rancher-images.txt -s x.x.x.x -d x.x.x.x:8088

hangar mirror -f ./rancher-images.txt.converted -s x.x.x.x -d x.x.x.x:8088 \
--repo-type=harbor --harbor-https=false --tls-verify=false \
-j 10 -a amd64,arm64 -o failed-list-test.txt --debug

hangar mirror-validate -f ./rancher-images.txt.converted -d x.x.x.x:8088 --tls-verify=false -j 10
```

Save Load
```
hangar save -f ./rancher-images.txt -d saved-images.tar.gz --part --part-size=1G --tls-verify=false -j 10

hangar load -s ./saved-images.tar.gz -d x.x.x.x \
--repo-type=harbor --harbor-https=false --default-project=library --tls-verify=false -j 10 

hangar load-validate -s ./saved-images.tar.gz -d x.x.x.x -j 10 --default-project=library --tls-verify=false

```


### harbor https（自签名）

mirror
```
hangar convert-list -i rancher-images.txt  -d private.registry.io

hangar mirror -f ./rancher-images.txt.converted d private.registry.io --repo-type=harbor  --tls-verify=false -j 10 

hangar mirror-validate -f ./rancher-images.txt.converted -d private.registry.io --tls-verify=false -j 10
```

save load

```
hangar save -f ./rancher-images.txt  -d saved-images.tar.gz --part --part-size=1G --tls-verify=false -j 10

hangar load -s ./saved-image-cache -d private.registry.io --compress=dir --repo-type=harbor --tls-verify=false -j 10 

hangar load-validate -s ./saved-image-cache -d private.registry.io --compress=dir -j 10 --default-project=library --tls-verify=false
```
