### ISSUE TITLE
[load] 支持从多个压缩包中 Load 容器镜像

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#22]
目前 Load 仅能从一个压缩包中加载镜像 blobs 上传至 Registry server，
参照 https://github.com/cnrancher/pandaria/issues/2950 中的方案2，调整 Load 的逻辑，支持从多个 tar 包中加载镜像。

**Comment by STARRY-S** [comment]
此功能已开发完毕并完成自测 & Validation Test。

Load 的改动部分可以参考 [此处文档](https://github.com/cnrancher/hangar/blob/v1.6.0-rc3/docs/zh_CN/load.md#%E5%8A%A0%E8%BD%BD%E4%B8%8D%E5%90%8C%E6%9E%B6%E6%9E%84%E7%9A%84%E9%95%9C%E5%83%8F%E5%8C%85) 的介绍。

----

可于 `v1.6.0-rc3` 及后续 RC 版本进行测试。
CC @rootwuj

**Comment by rootwuj** [comment]
版本：v1.6.0-rc6

在此版本按照  https://github.com/cnrancher/hangar/issues/22#issuecomment-1554243134 步骤验证通过。
