### ISSUE TITLE
[feature] 根据 KDM data.json 和 Rancher 版本号生成 k8s 版本信息

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#26]
## Generate k8s version list with KDM `data.json` and Rancher version

目前根据 KDM Data.json 获取某个 Rancher 版本支持的 rke2, k3s 版本信息的方式是手动部署一个 Rancher local 集群，比较麻烦，可以为 Hangar 新增这个功能。

----

Currently, the way to get the supported versions of K3s and RKE, RKE2 is to set up a Rancher local cluster manually.

Consider adding this feature for Hangar to generate a k8s version list with KDM `data.json` and Rancher version.

**Comment by STARRY-S** [comment]
## Design

`hangar generate-list` 子命令在输出镜像列表的同时，输出一份支持的 RKE1, RKE2, K3s 版本信息列表。

-----

The `hangar generate-list` subcommand will output a **RKE1, RKE2, K3s** version list file of Rancher when generating the Rancher image list.

**Comment by STARRY-S** [comment]
Available to test in `v1.7.1-beta.1`.

```sh
hangar generate-list --rancher="v2.8.0"

# v2.8.0-versions.txt
K3s, RKE2, RKE versions for Rancher v2.8.0:

K3s Versions:
v1.25.13+k3s1
v1.25.15+k3s2
v1.25.16+k3s4
v1.26.10+k3s2
v1.26.11+k3s2
v1.26.8+k3s1
v1.27.5+k3s1
v1.27.7+k3s2
v1.27.8+k3s2

RKE2 Versions:
v1.25.13+rke2r1
v1.25.15+rke2r2
v1.25.16+rke2r1
v1.26.10+rke2r2
v1.26.11+rke2r1
v1.26.8+rke2r1
v1.27.5+rke2r1
v1.27.7+rke2r2
v1.27.8+rke2r1

RKE Versions:
v1.25.16-rancher2-1
v1.26.11-rancher2-1
v1.27.8-rancher2-1
```

**Comment by dingluyy** [comment]
版本：v1.7.1-beta.1
验证通过。

1. hangar generate-list --rancher="" (`--kdm` / `--registry=""` / `-o` / `--output-source` / `--output-windows` / `--dev` / `--chart` / `--system-chart` )flag验证均通过，不再支持`--output-linux`。
2. hangar generate-list --rancher="v2.7.9-ent" 生成k8s版本信息
![截屏2024-01-09 下午2 40 47](https://github.com/cnrancher/hangar/assets/54788198/ac34eeb0-9a73-4a2d-9177-b199c7bc3287)
3. 移除旧版本`system-agent-installer-k3s/rke2`镜像。（对比1.7.0版本）
![截屏2024-01-09 下午2 00 03](https://github.com/cnrancher/hangar/assets/54788198/81984502-da5a-4483-9d20-89cb4d40ab8b)
