### ISSUE TITLE
[feature][archive] Export/merge images between archive files

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#32]
## Describe the solution you'd like

The hangar `archive` command can add following subcommands to improve user experience:

- `export` command to export images from the existing archive file into another archive.
- `merge` command to merge multiple archive files into one archive.

**Comment by STARRY-S** [comment]
Available to test in hangar `v1.7.1-beta.2`.

Documents:
merge: https://hangar.cnrancher.com/zh/docs/v1.7/archive/merge/
export: https://hangar.cnrancher.com/zh/docs/v1.7/archive/export

**Comment by dingluyy** [comment]
版本：v1.7.1-beta.3
验证通过。

hangar archive merge
---
### 数据准备
![截屏2024-01-12 下午3 56 26](https://github.com/cnrancher/hangar/assets/54788198/5649125f-39ec-4050-9b0b-446df9139bd7)
### 命令执行
1. 多个 archive文件merge为一个镜像包文件
![截屏2024-01-12 下午3 57 38](https://github.com/cnrancher/hangar/assets/54788198/a02751be-6ab1-41a6-ba90-582737c079ad)
2. 镜像包文件存在时，不自动覆盖
![截屏2024-01-12 下午3 58 54](https://github.com/cnrancher/hangar/assets/54788198/f26838b8-2193-4e05-98d6-f6c0246af7cd)
3. 镜像包文件存在时，自动覆盖
![截屏2024-01-12 下午3 59 37](https://github.com/cnrancher/hangar/assets/54788198/cc932d91-76b3-4195-9e53-cee685965c78)
### 验证merge镜像包镜像正确
![截屏2024-01-12 下午4 09 52](https://github.com/cnrancher/hangar/assets/54788198/e99da63c-140e-4a44-bd44-6131e3b60459)

hangar archive export
---
### 数据准备
![截屏2024-01-12 下午4 26 37](https://github.com/cnrancher/hangar/assets/54788198/e28fdf97-c2f4-43b1-abd5-8046f35a2315)
### 命令执行
1. 不指定source-registry，export一个新镜像包文件
![截屏2024-01-12 下午4 51 14](https://github.com/cnrancher/hangar/assets/54788198/259fc53d-e0a7-4a14-87a1-01349ce5eb41)
2. 指定source-registry；镜像包文件存在时，不自动覆盖，失败镜像输出到默认文件
![截屏2024-01-12 下午4 52 36](https://github.com/cnrancher/hangar/assets/54788198/ce144205-60bc-443f-ae3e-0c1922554b1b)
3. 指定source-registry；镜像包文件存在时，自动覆盖，失败镜像输出到自定义文件
![截屏2024-01-12 下午4 53 27](https://github.com/cnrancher/hangar/assets/54788198/8c9250b5-28cd-4438-a9ac-2ac0c07a95b6)
### 验证export镜像包镜像正确
![截屏2024-01-12 下午4 58 29](https://github.com/cnrancher/hangar/assets/54788198/35c8a595-c61c-4e16-a3fe-24167f2391f8)
