### ISSUE TITLE
[Feature][1.8] Container image CVE scanning & SBOM outputs by trivy

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#39]
## Is your feature request related to a problem?

Original Issue: https://github.com/cnrancher/hangar/issues/15

Split the **container image CVE scanning & SBOM outputs** functionality into this separate issue.

## Describe the solution you'd like

Add container image CVE scanning functions and SBOM output functions, and the hangar will perform as a trivy client.

Currently consider using the [aquasecurity/trivy](https://github.com/aquasecurity/trivy) library to implement these functions.

**Comment by STARRY-S** [comment]
## Changes

Add `scan` command to scan container image vulnerabilities and SPDX SBOM.

More detailed info is available in docs: https://hangar.cnrancher.com/docs/v1.8/scan/

**Comment by STARRY-S** [comment]
Available to test on `v1.8.0-rc2`.
Docs: https://hangar.cnrancher.com/docs/v1.8/scan/

**Comment by rootwuj** [comment]
Version: v1.8.0-rc3

Verification passed, the test content is as follows:


Test Case | Command | Steps | Expected | Results
-- | -- | -- | -- | --
Scan image vulnerabilities | hangar scan | Use hangar scan command to scan container image vulnerabilities | The scan is successful and the results are output to a file | PASS
Scan in Air-Gapped mode | --offline-scan | Follow the document steps to scan container images in an offline environment. | Can scan successfully in offline environment | PASS
Scan in trivy client mode |   | Use Hangar to scan images in trivy client mode. | Can scan successfully. | PASS
SBOM Output | --format | 1. The --format parameters are set to json/yaml/csv respectively.2. Set format to spdx-json | 1. The scan result file format is correct2. Can scan successfully. | PASS
