### ISSUE TITLE
[1.7][Feature] More options for the generate-list command

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#41]
Add more option for the `generate-list` command to allow user to reduce unneeded container images.

**Comment by STARRY-S** [comment]
## Changes

1. Add following options for the `generate-list` command to allow users to split the RKE/RKE2/K3s images separately:
    - `--rke-images`
    - `--rke2-images`
    - `--k3s-images`
    - `--rke2-windows-images`
1. Add the `--kdm-remove-deprecated` option (default `true`) to only output the latest k8s minor versions to reduce the unneeded deprecated k8s images.

**Comment by STARRY-S** [comment]
Available to test on `v1.7.3-rc2`, related docs:
https://hangar.cnrancher.com/zh/docs/v1.7/generate-list/#options-for-kdm-image-list-files

**Comment by rootwuj** [comment]
Verified in v1.7.3-rc2

1. Use the following parameters to output a separate image list of rke1/rke2/k3s, which is correct and consistent with the k8s version supported by the rancher UI.

    - `--rke-images`
    - `--rke2-images`
    - `--k3s-images`
    - `--rke2-windows-images`

2. The image list generated with the `--kdm-remove-deprecated=false` parameter includes the deprecated k8s version, and the list data is correct.
