### ISSUE TITLE
[feature] 已 Mirror/Load 的镜像校验

### ISSUE THREAD

**Issue by STARRY-S** [cnrancher/hangar#6]
添加新功能，对已 Mirror / Load 的镜像进行 Digest 校对、Manifest 列表信息比对等校验功能。

**Comment by STARRY-S** [comment]
Mirror 校验于 v1.3.0-rc4 实现，Load 校验于 v1.3.0-rc5 实现，相关使用文档：
- [mirror-validate](https://github.com/cnrancher/image-tools/blob/v1.3.0-rc5/docs/zh_CN/mirror-validate.md)
- [load-validate](https://github.com/cnrancher/image-tools/blob/v1.3.0-rc5/docs/zh_CN/load-validate.md)

**Comment by rootwuj** [comment]
问题记录：
1. 类似busybox这种push到library的镜像，在validate的时候会找不到
```
06:09:02 [INFO] [M_ID:1] [docker.io/busybox:latest] is manifest.list.v2
06:09:02 [ERRO] [M_ID:1] FAILED [docker.io/busybox:latest]
06:09:02 [ERRO] [M_ID:1] [harbor.wujing.site/busybox:latest]: destination manifest does not exists
```
![image](https://user-images.githubusercontent.com/42061003/211475751-19c73b99-52b1-431c-8c02-8674f701c158.png)

**Comment by STARRY-S** [comment]
> 问题记录：
> 
> 1. 类似busybox这种push到library的镜像，在validate的时候会找不到
> 
> ```
> 06:09:02 [INFO] [M_ID:1] [docker.io/busybox:latest] is manifest.list.v2
> 06:09:02 [ERRO] [M_ID:1] FAILED [docker.io/busybox:latest]
> 06:09:02 [ERRO] [M_ID:1] [harbor.wujing.site/busybox:latest]: destination manifest does not exists
> ```
> 
> ![image](https://user-images.githubusercontent.com/42061003/211475751-19c73b99-52b1-431c-8c02-8674f701c158.png)

于 https://github.com/cnrancher/image-tools/commit/92eee545ba45cfe0d5281e37ae0b8d2c721cb0fe 修复，可在下一 RC 版本测试。

**Comment by rootwuj** [comment]
> 问题记录：
> 
> 1. 类似busybox这种push到library的镜像，在validate的时候会找不到
> 
> ```
> 06:09:02 [INFO] [M_ID:1] [docker.io/busybox:latest] is manifest.list.v2
> 06:09:02 [ERRO] [M_ID:1] FAILED [docker.io/busybox:latest]
> 06:09:02 [ERRO] [M_ID:1] [harbor.wujing.site/busybox:latest]: destination manifest does not exists
> ```
> 
> ![image](https://user-images.githubusercontent.com/42061003/211475751-19c73b99-52b1-431c-8c02-8674f701c158.png)

此问题在v1.3.0-rc8验证通过。mirror validate可以通过。
```
root@ip-172-31-19-163:~# ./image-tools mirror-validate -f ./mirror-validate-failed.txt -d cluster.wujing.site -j 20
09:04:48 [INFO] Found skopeo: skopeo version 1.9.3
09:04:48 [INFO] Creating 20 job workers
09:04:50 [INFO] [M_ID:1] [docker.io/busybox:latest] is manifest.list.v2
09:04:50 [INFO] [M_ID:2] [docker.io/registry:2] is manifest.list.v2
09:04:50 [INFO] [M_ID:1] PASS [docker.io/busybox:latest] == [cluster.wujing.site/library/busybox:latest]
09:04:50 [INFO] [M_ID:2] PASS [docker.io/registry:2] == [cluster.wujing.site/library/registry:2]
root@ip-172-31-19-163:~#
```

**Comment by rootwuj** [comment]
版本：v1.3.0-rc8
镜像列表：v2.5.16-ent3 rancher-images.txt

验证通过。
mirror validate的验证：mirror镜像后validate可以通过。
```
# 修改格式
./image-tools convert-list -i rancher-images.txt -d harbor.wujing.site

# mirror
./image-tools mirror -f ./rancher-images.txt.converted -d harbor.wujing.site  -repo-type=harbor -default-project=library -j 20

# 校验
./image-tools mirror-validate -f ./rancher-images.txt.converted -d harbor.wujing.site -j 20 
```


load validate的验证：load镜像后validate可以通过。
```
# save
./image-tools save -f ./rancher-images.txt -d saved-images.tar.gz -j 20 

# load
./image-tools load -s ./saved-images.tar.gz -d harbor.wujing.site -repo-type=harbor -default-project=library -j 20 

# 校验
./image-tools load-validate -s ./saved-images.tar.gz -d harbor.wujing.site -j 20
```
